apiVersion: skaffold/v4beta13
kind: Config
build:
  local:
    push: true
    concurrency: 4
    useDockerCLI: true
    useBuildkit: false
  artifacts:
    - image: bahmansalehinic4/user
      context: backEnd/user
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
    
    - image: bahmansalehinic4/friendship
      context: backEnd/friendship
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
    - image: bahmansalehinic4/friend-suggestions
      context: backEnd/friend-suggestions
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts' 
    - image: bahmansalehinic4/media
      context: backEnd/media
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts' 
    - image: bahmansalehinic4/post
      context: backEnd/post
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts' 
    
    - image: bahmansalehinic4/feed
      context: backEnd/feed
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts' 
    
    - image: bahmansalehinic4/agent
      context: backEnd/agents
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts' 
    
    - image: bahmansalehinic4/room
      context: backEnd/room
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts' 
    
    - image: bahmansalehinic4/chat
      context: backEnd/chat
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts' 
    
    - image: bahmansalehinic4/realtime-gateway
      context: backEnd/realtime-gateway
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts' 
    
    - image: bahmansalehinic4/ai-gateway
      context: backEnd/ai/aiGateway
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
    - image: bahmansalehinic4/agent-manager
      context: backEnd/agent-manager
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts' 
    - image: bahmansalehinic4/api-gateway
      context: backEnd/api-gateway
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
    - image: bahmansalehinic4/search
      context: backEnd/search
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
    - image: bahmansalehinic4/chat-history
      context: backEnd/chat-history
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
    - image: bahmansalehinic4/ar-conversations
      context: backEnd/ar-conversations
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts' 
manifests:
  rawYaml: 
    # Phase 1: Infrastructure services (deployed first, in dependency order)
    - ./infra/k8s/redpanda-external-srv.yaml  # External service pointing to host Redpanda
    - ./infra/k8s/kafka-topics-init.yaml      # Initialize Kafka topics (Job)
    - ./infra/k8s/*-mongo-depl.yaml
    - ./infra/k8s/realtime-redis-depl.yaml
    - ./infra/k8s/redis-room-depl.yaml
    # (feedback service removed for MVP)
    # Phase 2: Application services (deployed after infrastructure)
    # Services with startup probes will wait for dependencies automatically
    - ./infra/k8s/auth-depl.yaml
    - ./infra/k8s/user*.yaml
    - ./infra/k8s/friendship-depl.yaml
    - ./infra/k8s/friend-suggestions-depl.yaml
    - ./infra/k8s/media-depl.yaml
    - ./infra/k8s/post-depl.yaml
    - ./infra/k8s/feed-depl.yaml
    - ./infra/k8s/search-depl.yaml
    - ./infra/k8s/room-depl.yaml
    - ./infra/k8s/chat-depl.yaml
    - ./infra/k8s/chat-history-depl.yaml
    - ./infra/k8s/ar-conversations-mongo-depl.yaml  # MongoDB BEFORE service
    - ./infra/k8s/ar-conversations-depl.yaml
    - ./infra/k8s/agent-depl.yaml
    - ./infra/k8s/agent-manager-mongo-depl.yaml  # MongoDB BEFORE service
    - ./infra/k8s/agent-manager-depl.yaml
    - ./infra/k8s/ai-gateway-depl.yaml
    - ./infra/k8s/realtime-gateway-depl.yaml
    - ./infra/k8s/api-gateway-depl.yaml
    # Phase 3: Ingress (deployed last)
    - ./infra/k8s/ingress-srv.yaml
deploy:
  statusCheckDeadlineSeconds: 600  # 10 minutes timeout for status checks (increased for slow-starting services)
  kubectl:
    # Manifests are applied in order, and services use readiness/startup probes
    # to wait for dependencies automatically
    flags:
      global: []
      apply: []
      delete: []

