apiVersion: skaffold/v4beta13
kind: Config
build:
  local:
    push: false
    concurrency: 1
  artifacts:
    - image: bahmansalehinic4/auth
      context: backEnd/auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
  
manifests:
  rawYaml: 
    - ./infra/k8s/*

