apiVersion: skaffold/v4beta13
kind: Config
build:
  local:
    push: false
    concurrency: 1
  artifacts:
    - image: bahmansalehinic4/user
      context: backEnd/user
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'
    
    - image: bahmansalehinic4/frontend
      context: frontEnd
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: '**/*.js'

    - image: bahmansalehinic4/ecommerce-models
      context: backEnd/ecommerce/aiModelCards
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'  
    - image: bahmansalehinic4/ecommerce-orders
      context: backEnd/ecommerce/orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts'  
    - image: bahmansalehinic4/order-expiration
      context: backEnd/ecommerce/expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts' 
    - image: bahmansalehinic4/friendship
      context: backEnd/friendship
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts' 
    - image: bahmansalehinic4/media
      context: backEnd/media
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts' 
    - image: bahmansalehinic4/post
      context: backEnd/post
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts' 
    
    - image: bahmansalehinic4/feed
      context: backEnd/feed
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts' 
    
    - image: bahmansalehinic4/agent
      context: backEnd/agents
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: 'src/**/*.ts' 
manifests:
  rawYaml: 
    - ./infra/k8s/*

