apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redpanda
spec:
  serviceName: redpanda
  replicas: 1  # change to 3 for production
  selector:
    matchLabels:
      app: redpanda
  template:
    metadata:
      labels:
        app: redpanda
    spec:
      containers:
        - name: redpanda
          image: redpandadata/redpanda:latest
          args:
            - redpanda
            - start
            - --mode dev-container
            - --smp 1
            - --overprovisioned
            - --node-id 0
            - --kafka-addr PLAINTEXT://0.0.0.0:9092
            - --advertise-kafka-addr PLAINTEXT://redpanda-srv:9092
            - --memory 512M
            - --reserve-memory 0M
          ports:
            - containerPort: 9092   # Kafka API
            - containerPort: 9644   # Admin API
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          startupProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 12  # Allow up to 60 seconds (12 * 5) for startup
          readinessProbe:
            httpGet:
              path: /v1/status/ready
              port: 9644
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 6
          livenessProbe:
            tcpSocket:
              port: 9092
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: redpanda-srv
spec:
  selector:
    app: redpanda
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
