apiVersion: apps/v1
kind: Deployment
metadata:
  name: room-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: room
  template:
    metadata:
      labels:
        app: room
    spec:
      containers:
        - name: room
          image: bahmansalehinic4/room
          env:  
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: "aichatwar"
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
        
            - name: KAFKA_BROKER_URL
              value: 'redpanda-srv:9092'
              
            - name: KAFKA_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MONGO_URI
              value: "mongodb://room-mongo-srv:27017/room"
            - name: JWT_DEV
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_DEV
---
apiVersion: v1
kind: Service
metadata:
  name: room-srv
spec:
  selector:
    app: room
  ports:
    - name: room
      protocol: TCP
      port: 3000
      targetPort: 3000
